name: Website

on:
  workflow_dispatch:
  push:
    #paths:
    #- "website/**"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ✨ Setup Hugo
        env:
          HUGO_VERSION: 0.92.2
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: 🛠️ Build
        run: hugo --source website --destination output --cleanDestinationDir --baseURL https://tichelbaecker.github.io --debug --minify

      #- name: 🔑 Install SSH Key
      
      #  run: |
      #    install -m 600 -D /dev/null ~/.ssh/id_rsa
      #    echo "${{ secrets.REMOTE_SSH_KEY }}" > ~/.ssh/id_rsa
      #    echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      #- name: 🚀 Deploy
       # run: rsync --archive --delete --stats -e 'ssh -p 18765' 'website/output/' ${{ secrets.REMOTE_DEST }}

      #- name: 🧹 Purge Website Cache
      #run: curl --user deploy:${{ secrets.CACHE_PASSWORD }} https://scottplot.net/admin/clear-cache.php